MarkText
Notepadpp
VisualStudioCommunityEdition
AnyBurn
Etcher
OBSStudio
Rufus
VLC
Perl
JDownloader
qBittorrent
WinSCP
Wireshark
CyberDuck
Exterro FTK Imager
ExifToolGUI
HxD
IrfanView
Photorec
Sqlitebrowser
XstReader
hasher
SecureRM
BuildTools
Everything
PowerShell
PowerToys
WindowsTerminal
ClamAVWin
ChocolateyGUI
DockerDesktop
Chrome
Firefox
CMake
Git
VisualStudioCode
CoreTemp
CrystalDiskInfo
ProtonDrive
ProtonMail
ProtonPass
ProtonVPN
Resourcehacker.portable
SpaceSniffer
Sysinternals
WinDirStat
EditPadLite
KeePass
Thunderbird
CyberChef
Eraser
Mailviewer
NvidiaApp
AshampooBUPro15
LibreOffice
Obsidian
PDF24Creator
VisioViewer
WSL
WSL Update
VMware Workstation
BurnInTest
GSmartControl
