ExifToolGUI
hasher
HxD
IrfanView
Photorec
SecureRM
Sqlitebrowser
XstReader
AshampooBUPro15
Chrome
Firefox
CyberChef
CMake
Git
VisualStudioCode
VisualStudioCommunityEdition
MarkText
Notepadpp
Mailviewer
ClamAVWin
AnyBurn
Etcher
OBSStudio
Rufus
VLC
CyberDuck
JDownloader
qBittorrent
WinSCP
Wireshark
LibreOffice
Obsidian
PDF24Creator
VisioViewer
Perl
BuildTools
BurnInTest
ChocolateyGUI
CoreTemp
CrystalDiskInfo
DockerDesktop
EditPadLite
Everything
GSmartControl
KeePass
NvidiaApp
PowerShell
PowerToys
ProtonDrive
ProtonMail
ProtonPass
ProtonVPN
Resourcehacker.portable
SpaceSniffer
Sysinternals
VMware Workstation17
W10Privacy
WinDirStat
WindowsTerminal
Eraser
Thunderbird
Ubuntu2204
WSL
WSL Update
